### ISSUE TITLE
ValueError: --share-all-embeddings requires a joined dictionary

### ISSUE THREAD

**Issue by EricLina** [ictnlp/GMA#1]
with data-bin prepared by 
> fairseq-preprocess --source-lang ${src} --target-lang ${tgt} \
>  --trainpref ${train_data} --validpref ${vaild_data} \
>    --testpref ${test_data}\
>    --destdir ${data} \
>   --workers 20

When I use the command below  
`python train.py --ddp-backend=no_c10d ${data} --arch transformer --share-all-embeddings \
--optimizer adam \
--adam-betas '(0.9, 0.98)' \
--clip-norm 0.0 \
--lr 5e-4 \
--lr-scheduler inverse_sqrt \
--warmup-init-lr 1e-07 \
--warmup-updates 4000 \
--dropout 0.3 \
--criterion label_smoothed_cross_entropy \
--label-smoothing 0.1 \
--left-pad-source False \
--delta ${delta} \
--save-dir ${modelfile} \
--max-tokens 4096 --update-freq 2`

It will get an error :
`  File "/share03/zhangzs/kh/liang/Reproduce2022/GMA/fairseq/models/transformer.py", line 154, in build_model
    raise ValueError("--share-all-embeddings requires a joined dictionary")
ValueError: --share-all-embeddings requires a joined dictionary`

I guess we need to prepare the data-bin with "--joined-dictionary" ,right ?

**Comment by zhangshaolei1998** [comment]
Yes, `--joined-dictionary` is required for WMT15 German-English, thanks for the reminder and we have already updated it.
