### ISSUE TITLE
training go wrong

### ISSUE THREAD

**Issue by xiaohangguo** [ictnlp/GMA#3]
Hello, I want to reproduce your results, but when I went to the second step (training), I encountered some problems related to the dictionary. I don't know how to solve it. How should I do it?

 **my command**

>delta=1.0
 >modelfile=/root/model
 >data=/root/data2

>python train.py --ddp-backend=no_c10d ${data} --arch transformer --share-all-embeddings \
 >--optimizer adam \
 >--adam-betas '(0.9, 0.98)' \
> --clip-norm 0.0 \
 >--lr 5e-4 \
> --lr-scheduler inverse_sqrt \
> --warmup-init-lr 1e-07 \
> --warmup-updates 4000 \
> --dropout 0.3 \
> --criterion label_smoothed_cross_entropy \
> --label-smoothing 0.1 \
 >--left-pad-source False \
> --delta ${delta} \
> --save-dir ${modelfile} \
> --max-tokens 4096 --update-freq 2

Reported an error related to the dictionary. I don't know how to deal with it.

>| [de] dictionary: 34928 types
>| [en] dictionary: 33176 types
>| loaded 2919 examples from: /root/data2/valid.de-en.de
>| loaded 2919 examples from: /root/data2/valid.de-en.en
>| /root/data2 valid de-en 2919 examples
>Traceback (most recent call last):
> File "/root/GMA/train.py", line 365, in <module>
>  cli_main()
 > File "/root/GMA/train.py", line 361, in cli_main
 >   main(args)
 > File "/root/GMA/train.py", line 59, in main
  >  model = task.build_model(args)
  >File "/root/GMA/fairseq/tasks/fairseq_task.py", line 201, in build_model
   > return models.build_model(args, self)
 > File "/root/GMA/fairseq/models/__init__.py", line 48, in build_model
  >  return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
 > File "/root/GMA/fairseq/models/transformer.py", line 154, in build_model
  >  raise ValueError("--share-all-embeddings requires a joined dictionary")
>ValueError: --share-all-embeddings requires a joined dictionary

**Comment by zhangshaolei1998** [comment]
When processing the data into the fairseq format, you should add `--joined-dictionary` for WMT15 German-English:

**Comment by xiaohangguo** [comment]
ok，Thank u. I soved it.
